# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "e+SKNaXlxS5MxRmrRqkuPz8I6MnBv4FG/XuQw1DMKby1qLLs54BGpFT57DyY9xz/Tbv/Mz4/PNLz3Nq+Y0h31dEIdMgB4ul5cQOfxixxCKWKqW+BMsucJ3egaMRGwDYqvzNq6U6iVtsOxK8BOXrtZXAI/tyjsUuwx+SBRWN8BaF+cpr+iINo8CY89/lPep9WIe2xzsjAwM3euMSNOJJ9xbpYUF2rYyYOjnrOGMvPCQ0qJfKCg+d7jkZKPDN6fPjhTarTMmLiEYX6i2P8SsBOUDlgXr9Wz9lgzubF4XQMw3mqPXofHhJYATnt3gM2/PdBD2SnA0ioJ9J4vrgZu8I5wg19epk5hZkk0t24elDNSeZVCW4+/ACdM/3vZeSolCK68zP/YZuV84v4jCeADlABJONX2LyVJ6o9JzkNDemQptpfbtSboKic/PLKXkA7mfaq6S1JSMAfui7AvCpPlnmrywRsJDlefP50IaNf3byPu4UsbM7YwJe6mdKKf9MRBs/7/+Lp1Nk920hGz/wFh1A3p6zGsR/oTKr1hYycpvv+0IHRnZvbB2CSqrkYDNqOyYt8xlHc3Fi3U9m+VwYzPetYBpUwo3SGKqzH9dNtF29r1KKITQlkH1hgFRuPr7ekcaqzCDU/yqz+AEDbcsQYX51yR7aoDwLwDpSk+DKpuQLE0gs="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
